/**
 * Common constants for all features.
 */
export class CommonConstants {
  /**
   * Breakpoint sm.
   */
  static readonly BREAKPOINTS_SM_NAME: string = 'sm';

  /**
   * Breakpoint md.
   */
  static readonly BREAKPOINTS_MD_NAME: string = 'md';

  /**
   * Breakpoint lg.
   */
  static readonly BREAKPOINTS_LG_NAME: string = 'lg';

  /**
   * Breakpoint xl.
   */
  static readonly BREAKPOINTS_XL_NAME: string = 'xl';

  /**
   * The value of tab vertical in sm device.
   */
  static readonly TAB_SM_VERTICAL: boolean = false;

  /**
   * The value of tab vertical in md device.
   */
  static readonly TAB_MD_VERTICAL: boolean = false;

  /**
   * The value of tab vertical in lg device.
   */
  static readonly TAB_LG_VERTICAL: boolean = true;

  /**
   * The value of tab vertical in xl device.
   */
  static readonly TAB_XL_VERTICAL: boolean = true;

  /**
   * The percentage of width of tab bar in sm device.
   */
  static readonly TAB_SM_BAR_WIDTH: string = '100%';

  /**
   * The percentage of width of tab bar in md device.
   */
  static readonly TAB_MD_BAR_WIDTH: string = '100%';

  /**
   * The width of tab bar in lg device.
   */
  static readonly TAB_LG_BAR_WIDTH: string = '96vp';

  /**
   * The width of tab bar in xl device.
   */
  static readonly TAB_XL_BAR_WIDTH: string = '96vp';

  /**
   * The height of tab bar in sm device.
   */
  static readonly TAB_SM_BAR_HEIGHT: string = '56vp';

  /**
   * The height of tab bar in md device.
   */
  static readonly TAB_MD_BAR_HEIGHT: string = '56vp';

  /**
   * The percentage of height tab bar in lg device.
   */
  static readonly TAB_LG_BAR_HEIGHT: string = '60%';

  /**
   * The percentage of height tab bar in xl device.
   */
  static readonly TAB_XL_BAR_HEIGHT: string = '60%';

  /**
   * The percentage of width of tab content.
   */
  static readonly TAB_CONTENT_WIDTH: string = '100%';

  /**
   * The percentage of height of tab content.
   */
  static readonly TAB_CONTENT_HEIGHT: string = '100%';

  /**
   * The percentage of width of flex component.
   */
  static readonly FLEX_TAB_BAR_WIDTH: string = '100%';

  /**
   * The percentage of height of flex component.
   */
  static readonly FLEX_TAB_BAR_HEIGHT: string = '100%';

  /**
   * The percentage of height in row component.
   */
  static readonly FIRST_TAB_CHOOSE_INDEX: number = 0;

  /**
   * The percentage of height in row component.
   */
  static readonly COLUMN_HEIGHT: string = '100%';

  /**
   * The number of tab component.
   */
  static readonly TAB_SIZE: number = 2;

  /**
   * Initialize device breakpoints.
   */
  static readonly BREAKPOINTS_INITIALIZE_NAME: string = 'md';

  /**
   *  The value of aspect ratio in column component.
   */
  static readonly COLUMN_ASPECT_RATIO: number = 16 / 9;

  /**
   * Font weight of text component.
   */
  static readonly COLUMN_TEXT_FONT_WEIGHT: number = 400;

  /**
   *  The percentage of width of row component.
   */
  static readonly ROW_WIDTH: string = '100%';

  /**
   * The value of  attribute of columnsTemplate in sm device.
   */
  static readonly SM_COL_TEMPLATE: string = '1fr 1fr';

  /**
   * The value of  attribute of columnsTemplate in md device.
   */
  static readonly MD_COL_TEMPLATE: string = '1fr 1fr 1fr';

  /**
   * The value of  attribute of columnsTemplate in lg device.
   */
  static readonly LG_COL_TEMPLATE: string = '1fr 1fr 1fr 1fr';

  /**
   * The value of  attribute of columnsTemplate in xl device.
   */
  static readonly XL_COL_TEMPLATE: string = '1fr 1fr 1fr 1fr';

  /**
   * Initialization of attribute columnsTemplate.
   */
  static readonly INITIALIZE_TEMPLATE: string = '1fr 1fr';

  /**
   * Breakpoint name.
   */
  static readonly BREAKPOINT_SYSTEM_NAME: string = 'mainBreakpoint';
}
