/**
 * Common constants for all features.
 */
export class CommonConstants {
  /**
   * The percentage of width in row component.
   */
  static readonly COLUMN_WIDTH: string = '100%';

  /**
   * The percentage of height in row component.
   */
  static readonly COLUMN_HEIGHT: string = '100%';

  /**
   * The value of number of the flex shrink.
   */
  static readonly COLUMN_FLEX_SHRINK: number = 1;

  /**
   * The percentage of width.
   */
  static readonly WIDTH: string = '100%';

  /**
   * The percentage of height.
   */
  static readonly HEIGHT: string = '100%';

  /**
   * The minimum rolling value of the slider.
   */
  static readonly SLIDER_MIN: number = 55;

  /**
   * The maximum rolling value of the slider.
   */
  static readonly SLIDER_MAX: number = 90;

  /**
   * The margin between the slider and the bottom.
   */
  static readonly SLIDER_MARGIN: number = 24;

  /**
   * The percent sign.
   */
  static readonly PERCENT_SIGN: string = '%';
}