/**
 * Common constants for all features.
 */
export class CommonConstants {
  /**
   * The number of columns for XS device.
   */
  static readonly COLUMN_XS: number = 4;

  /**
   * The number of columns for SM device.
   */
  static readonly COLUMN_SM: number = 4;

  /**
   * The number of columns for MD device.
   */
  static readonly COLUMN_MD: number = 8;

  /**
   * The number of columns for LG device.
   */
  static readonly COLUMN_LG: number = 12;

  /**
   * The number of span for XS device.
   */
  static readonly SPAN_XS: number = 4;

  /**
   * The number of span for SM device.
   */
  static readonly SPAN_SM: number = 4;

  /**
   * The number of span for MD device.
   */
  static readonly SPAN_MD: number = 4;

  /**
   * The number of span for LG device.
   */
  static readonly SPAN_LG: number = 4;

  /**
   * The number of offset for XS device.
   */
  static readonly OFFSET_XS: number = 0;

  /**
   * The number of offset for SM device.
   */
  static readonly OFFSET_SM: number = 0;

  /**
   * The number of offset for MD device.
   */
  static readonly OFFSET_MD: number = 2;

  /**
   * The number of offset for LG device.
   */
  static readonly OFFSET_LG: number = 4;

  /**
   * Font weight of the list.
   */
  static readonly LIST_FONT_WEIGHT: number = 500;

  /**
   *Width of the list.
   */
  static readonly LIST_WIDTH: string = '100%';

  /**
   * The percentage of width of the list item.
   */
  static readonly LIST_ITEM_WIDTH: string = '100%';

  /**
   * The percentage of height of the column.
   */
  static readonly COLUMN_HEIGHT: string = '100%';

  /**
   * The name of the bundleName.
   */
  static readonly BUNDLE_NAME: string = 'com.example.myapplication';

  /**
   * The name of the abilityName.
   */
  static readonly ABILITY_NAME: string = 'ResponsiveLayoutItemAbility';

  /**
   * Initialize device breakpoints.
   */
  static readonly BREAKPOINTS_INITIALIZE_NAME: string = 'md';

  /**
   * Localization ability.
   */
  static readonly LOCATION_CAPABILITY: string = 'SystemCapability.Location.Location.Core';

  /**
   * Breakpoint name.
   */
  static readonly BREAKPOINT_SYSTEM_NAME: string = 'mainBreakpoint';

  /**
   * The percentage of height of column component.
   */
  static readonly SYSTEM_COLUMN_HEIGHT: string = '100%';

  /**
   * The percentage of width of column component.
   */
  static readonly SYSTEM_COLUMN_WIDTH: string = '100%';

  /**
   * The percentage of width of row component.
   */
  static readonly SYSTEM_ROW_WIDTH: string = '100%';

  /**
   * Font weight of text component.
   */
  static readonly TEXT_FONT_WEIGHT: number = 500;

  /**
   * The percentage of width of column component.
   */
  static readonly ADAPTIVE_COLUMN_WIDTH: string = '100%';

  /**
   * The percentage of height of column component.
   */
  static readonly ADAPTIVE_COLUMN_HEIGHT: string = '100%';

  /**
   * The percentage of height of column component.
   */
  static readonly ADAPTIVE_FLEXIBLE_COLUMN_WIDTH: string = '100%';

  /**
   * The value of shrink of column component.
   */
  static readonly ADAPTIVE_FLEX_SHRINK: number = 1;
}