/**
 * Route constants for Router.
 */
export class RouteConstants {
  /**
   * Route of page for the ResponsiveLayout.
   */
  static readonly RESPONSIVE_ROUTE: string = 'pages/ResponsiveIndex';

  /**
   * Route of page for the AdaptiveLayout.
   */
  static readonly ADAPTIVE_ROUTE: string = 'pages/AdaptiveIndex';

  /**
   * Route of page for the SystemCapabilities.
   */
  static readonly SYSTEM_CAPABILITIES_ROUTE: string = 'pages/SystemCapabilitiesIndex';
}